name: autify_web
description: "Landing page per Autify.it — Analisi Dati per Autismo"
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
